import type { BlogPost, PricingPlan } from "@/types";

export const DEMO_USERS = [
  {
    id: "demo-user-1",
    email: "demo@shotnotes.com",
    password: "123456",
    name: "Alex Johnson",
    role: "user" as const,
    plan: "pro" as const,
    avatar: "https://i.pravatar.cc/150?img=12",
    createdAt: "2024-01-15T10:00:00Z",
    notesCount: 47,
    storageUsed: 128,
  },
  {
    id: "admin-1",
    email: "admin@shotnotes.com",
    password: "admin123",
    name: "Sarah Admin",
    role: "admin" as const,
    plan: "enterprise" as const,
    avatar: "https://i.pravatar.cc/150?img=5",
    createdAt: "2023-08-01T09:00:00Z",
    notesCount: 0,
    storageUsed: 0,
  },
];

export const NOTE_COLORS = [
  "#8CE4FF20",
  "#FEEE9120",
  "#FFA23920",
  "#FF565620",
  "#A78BFA20",
  "#34D39920",
];

export const NOTE_COLOR_BORDERS = [
  "rgba(140,228,255,0.4)",
  "rgba(254,238,145,0.4)",
  "rgba(255,162,57,0.4)",
  "rgba(255,86,86,0.4)",
  "rgba(167,139,250,0.4)",
  "rgba(52,211,153,0.4)",
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Starter",
    price: 0,
    period: "forever",
    description: "Perfect for casual note-takers",
    features: [
      "50 notes per month",
      "Text notes only",
      "Basic search",
      "Mobile app access",
      "2 GB storage",
    ],
    notFeatures: [
      "Voice notes",
      "Image OCR",
      "AI summaries",
      "Collaboration",
      "Priority support",
    ],
    highlighted: false,
    color: "sky-blue",
  },
  {
    id: "pro",
    name: "Pro",
    price: 599,
    period: "month",
    description: "For serious productivity enthusiasts",
    features: [
      "Unlimited notes",
      "Text + Voice + Image notes",
      "AI summaries & keywords",
      "OCR text extraction",
      "Advanced search & tags",
      "Reminders & alerts",
      "15 GB storage",
      "Priority support",
    ],
    notFeatures: [
      "Team collaboration",
      "Admin dashboard",
    ],
    highlighted: true,
    badge: "Most Popular",
    color: "brand-orange",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 1499,
    period: "month",
    description: "For teams and organizations",
    features: [
      "Everything in Pro",
      "Team collaboration",
      "Admin dashboard",
      "Role-based access",
      "Analytics & insights",
      "Custom integrations",
      "100 GB storage",
      "Dedicated support",
      "SLA guarantee",
    ],
    notFeatures: [],
    highlighted: false,
    color: "coral-red",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "10 Note-Taking Strategies That Will Boost Your Productivity",
    excerpt: "Discover science-backed methods to capture ideas faster and retain information longer.",
    content: `Note-taking is a skill that separates high achievers from the rest. Whether you're a student, professional, or entrepreneur, mastering note-taking can dramatically improve your productivity and recall. Here are 10 proven strategies...`,
    author: "Dr. Priya Sharma",
    authorAvatar: "https://i.pravatar.cc/150?img=23",
    category: "Productivity",
    tags: ["productivity", "note-taking", "tips"],
    imageUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    readTime: 7,
    publishedAt: "2024-12-15T10:00:00Z",
    views: 12400,
  },
  {
    id: "2",
    title: "How AI is Revolutionizing the Way We Organize Information",
    excerpt: "Explore how artificial intelligence transforms scattered notes into structured knowledge.",
    content: `Artificial intelligence is no longer just a buzzword — it's fundamentally changing how we process and retain information. From smart summaries to automated tagging...`,
    author: "Rahul Mehta",
    authorAvatar: "https://i.pravatar.cc/150?img=33",
    category: "AI & Technology",
    tags: ["AI", "technology", "organization"],
    imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    readTime: 9,
    publishedAt: "2024-12-10T10:00:00Z",
    views: 8900,
  },
  {
    id: "3",
    title: "Voice Notes vs Text Notes: Which is Better for Memory?",
    excerpt: "A deep dive into how different note formats affect comprehension and long-term memory.",
    content: `The debate between voice and text notes has been ongoing in productivity circles. New research from cognitive psychology sheds light on which format actually helps you remember more...`,
    author: "Ananya Patel",
    authorAvatar: "https://i.pravatar.cc/150?img=44",
    category: "Research",
    tags: ["voice notes", "memory", "research"],
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80",
    readTime: 5,
    publishedAt: "2024-12-05T10:00:00Z",
    views: 6700,
  },
  {
    id: "4",
    title: "The Ultimate Guide to Visual Note-Taking with OCR",
    excerpt: "Learn how to capture whiteboard sessions, textbooks, and handwritten notes digitally.",
    content: `Visual note-taking has always been powerful, but OCR (Optical Character Recognition) takes it to a whole new level. Instead of manually transcribing what you see...`,
    author: "Vikram Singh",
    authorAvatar: "https://i.pravatar.cc/150?img=60",
    category: "Tutorial",
    tags: ["OCR", "visual", "tutorial"],
    imageUrl: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=800&q=80",
    readTime: 12,
    publishedAt: "2024-11-28T10:00:00Z",
    views: 4300,
  },
  {
    id: "5",
    title: "Building a Second Brain: ShotNotes as Your External Memory",
    excerpt: "How to use ShotNotes to create a comprehensive personal knowledge management system.",
    content: `The concept of a 'second brain' — an external system that stores and organizes all your knowledge — is gaining massive traction in productivity circles. ShotNotes...`,
    author: "Kavya Reddy",
    authorAvatar: "https://i.pravatar.cc/150?img=47",
    category: "Productivity",
    tags: ["second brain", "PKM", "productivity"],
    imageUrl: "https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=800&q=80",
    readTime: 8,
    publishedAt: "2024-11-20T10:00:00Z",
    views: 9200,
  },
  {
    id: "6",
    title: "Top 5 Features Students Love About ShotNotes",
    excerpt: "From lecture capture to AI summaries, discover why students are switching to ShotNotes.",
    content: `Students face unique challenges when it comes to note-taking. Keeping up with fast-paced lectures, organizing material for exams, and retaining key concepts...`,
    author: "Arjun Kumar",
    authorAvatar: "https://i.pravatar.cc/150?img=70",
    category: "Case Study",
    tags: ["students", "education", "features"],
    imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
    readTime: 6,
    publishedAt: "2024-11-15T10:00:00Z",
    views: 7800,
  },
];

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Product Designer at Zomato",
    avatar: "https://i.pravatar.cc/150?img=23",
    rating: 5,
    text: "ShotNotes completely changed my workflow. The AI summaries save me at least 2 hours every day. The voice-to-text is incredibly accurate, even in noisy environments!",
  },
  {
    id: "2",
    name: "Arjun Mehta",
    role: "MBA Student, IIM Bangalore",
    avatar: "https://i.pravatar.cc/150?img=33",
    rating: 5,
    text: "I capture lecture notes via voice, and ShotNotes turns them into organized, tagged notes instantly. It's like having a personal assistant that never sleeps.",
  },
  {
    id: "3",
    name: "Sneha Patel",
    role: "Freelance Journalist",
    avatar: "https://i.pravatar.cc/150?img=47",
    rating: 5,
    text: "The OCR feature is a game-changer for my research. I photograph printed documents and ShotNotes extracts the text within seconds. Absolutely love this app!",
  },
  {
    id: "4",
    name: "Vikram Rajan",
    role: "Startup Founder",
    avatar: "https://i.pravatar.cc/150?img=60",
    rating: 5,
    text: "We use ShotNotes Enterprise for our entire team. The collaboration features and admin controls are fantastic. Our team's productivity went up by 40% in the first month.",
  },
  {
    id: "5",
    name: "Ananya Krishnan",
    role: "Research Scientist",
    avatar: "https://i.pravatar.cc/150?img=44",
    rating: 5,
    text: "The keyword extraction and AI tagging are phenomenal. I can find any note from 3 years ago in seconds. ShotNotes is the backbone of my research process.",
  },
  {
    id: "6",
    name: "Rohit Shetty",
    role: "Content Creator, 2M followers",
    avatar: "https://i.pravatar.cc/150?img=68",
    rating: 5,
    text: "I brainstorm everything in ShotNotes — ideas, scripts, social posts. The AI suggests connections between notes that I'd never have made myself. Pure magic!",
  },
];

export const FAQS = [
  {
    q: "Is ShotNotes free to use?",
    a: "Yes! ShotNotes has a free Starter plan with 50 notes per month and 2 GB storage. Upgrade to Pro or Enterprise for unlimited notes, voice recording, OCR, and AI features.",
  },
  {
    q: "How accurate is the voice-to-text feature?",
    a: "Our voice-to-text engine achieves 97%+ accuracy for clear speech and supports 12 languages including Hindi, English, Tamil, Telugu, and more.",
  },
  {
    q: "Can I use ShotNotes offline?",
    a: "Yes! The mobile app supports offline mode. Notes you create offline automatically sync when you reconnect to the internet.",
  },
  {
    q: "How does the AI summary work?",
    a: "Our AI analyzes your note's content and generates a concise summary, extracts key points, suggests relevant tags, and identifies action items automatically.",
  },
  {
    q: "Is my data secure?",
    a: "Absolutely. All notes are encrypted with AES-256 encryption at rest and TLS 1.3 in transit. We are SOC 2 Type II certified and GDPR compliant.",
  },
  {
    q: "Can I share notes with others?",
    a: "Yes! You can share individual notes via secure links, collaborate in real-time on shared notes, and control view/edit permissions for each collaborator.",
  },
  {
    q: "What file formats does OCR support?",
    a: "OCR works with JPG, PNG, HEIC, PDF, and even photos taken directly through the camera. It can extract text from handwritten notes too.",
  },
  {
    q: "Can I cancel my subscription anytime?",
    a: "Yes, you can cancel anytime from your account settings. Your subscription remains active until the end of the billing period, and no refunds are issued for partial months.",
  },
];

export const STATS = [
  { value: 500000, label: "Active Users", suffix: "+" },
  { value: 25000000, label: "Notes Created", suffix: "+" },
  { value: 97, label: "Voice Accuracy", suffix: "%" },
  { value: 4.9, label: "App Store Rating", suffix: "/5", decimal: true },
  { value: 150, label: "Countries", suffix: "+" },
  { value: 99.9, label: "Uptime SLA", suffix: "%", decimal: true },
];
